apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-chatbot-chart.fullname" . }}-backend
  labels:
    app: {{ include "todo-chatbot-chart.name" . }}-backend
    chart: {{ include "todo-chatbot-chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "todo-chatbot-chart.name" . }}-backend
    release: {{ .Release.Name }}